export interface Country {
  code: string    // 'FR'
  name: string    // 'France'
  flag: string    // '🇫🇷'
  dialCode: string // '+33'
}

export const COUNTRIES: Country[] = [
  { code: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', dialCode: '+1' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', dialCode: '+32' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', dialCode: '+41' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', dialCode: '+1' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', dialCode: '+230' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', dialCode: '+49' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', dialCode: '+34' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', dialCode: '+39' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', dialCode: '+44' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', dialCode: '+31' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', dialCode: '+351' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', dialCode: '+353' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', dialCode: '+43' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', dialCode: '+45' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', dialCode: '+46' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', dialCode: '+47' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', dialCode: '+358' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', dialCode: '+354' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', dialCode: '+48' },
  { code: 'CZ', name: 'Tchéquie', flag: '🇨🇿', dialCode: '+420' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', dialCode: '+36' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', dialCode: '+421' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', dialCode: '+386' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', dialCode: '+385' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', dialCode: '+40' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', dialCode: '+359' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', dialCode: '+30' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾', dialCode: '+357' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹', dialCode: '+356' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', dialCode: '+372' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', dialCode: '+371' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', dialCode: '+370' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺', dialCode: '+7' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', dialCode: '+380' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', dialCode: '+375' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', dialCode: '+373' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', dialCode: '+387' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', dialCode: '+381' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', dialCode: '+382' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', dialCode: '+389' },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', dialCode: '+355' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', dialCode: '+90' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦', dialCode: '+212' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿', dialCode: '+213' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳', dialCode: '+216' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', dialCode: '+20' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', dialCode: '+27' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', dialCode: '+221' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', dialCode: '+225' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', dialCode: '+233' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', dialCode: '+234' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', dialCode: '+254' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', dialCode: '+251' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', dialCode: '+255' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', dialCode: '+256' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', dialCode: '+250' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', dialCode: '+265' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', dialCode: '+267' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦', dialCode: '+264' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', dialCode: '+244' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', dialCode: '+258' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', dialCode: '+261' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', dialCode: '+223' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', dialCode: '+227' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', dialCode: '+235' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', dialCode: '+236' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', dialCode: '+237' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', dialCode: '+240' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', dialCode: '+241' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', dialCode: '+242' },
  { code: 'CD', name: 'Congo (RDC)', flag: '🇨🇩', dialCode: '+243' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳', dialCode: '+86' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', dialCode: '+91' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', dialCode: '+81' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', dialCode: '+82' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', dialCode: '+66' },
  { code: 'VN', name: 'Viêt Nam', flag: '🇻🇳', dialCode: '+84' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', dialCode: '+60' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', dialCode: '+65' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', dialCode: '+63' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', dialCode: '+62' },
  { code: 'AU', name: 'Australie', flag: '🇦🇺', dialCode: '+61' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', dialCode: '+64' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', dialCode: '+679' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', dialCode: '+972' },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦', dialCode: '+966' },
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪', dialCode: '+971' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', dialCode: '+965' },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', dialCode: '+973' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', dialCode: '+962' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', dialCode: '+961' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', dialCode: '+963' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', dialCode: '+964' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', dialCode: '+98' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', dialCode: '+92' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94' },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', dialCode: '+977' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', dialCode: '+975' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', dialCode: '+960' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', dialCode: '+998' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', dialCode: '+992' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', dialCode: '+996' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', dialCode: '+993' },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳', dialCode: '+976' },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵', dialCode: '+850' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', dialCode: '+95' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', dialCode: '+856' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', dialCode: '+855' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', dialCode: '+886' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', dialCode: '+852' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', dialCode: '+853' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', dialCode: '+55' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', dialCode: '+54' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', dialCode: '+56' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', dialCode: '+51' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', dialCode: '+57' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', dialCode: '+593' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', dialCode: '+591' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', dialCode: '+592' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', dialCode: '+597' },
  { code: 'GF', name: 'Guyane française', flag: '🇬🇫', dialCode: '+594' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', dialCode: '+52' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', dialCode: '+502' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', dialCode: '+501' },
  { code: 'SV', name: 'Salvador', flag: '🇸🇻', dialCode: '+503' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', dialCode: '+504' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', dialCode: '+507' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', dialCode: '+53' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹', dialCode: '+509' },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴', dialCode: '+1809' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', dialCode: '+1876' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', dialCode: '+1868' },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧', dialCode: '+1246' },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨', dialCode: '+1758' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨', dialCode: '+1784' },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩', dialCode: '+1473' },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲', dialCode: '+1767' },
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬', dialCode: '+1268' },
  { code: 'KN', name: 'Saint-Kitts-et-Nevis', flag: '🇰🇳', dialCode: '+1869' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', dialCode: '+1242' },
  { code: 'BM', name: 'Bermudes', flag: '🇧🇲', dialCode: '+1441' }
]

function normalizeForSearch(text: string): string {
  return text.normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
}

export function getCountry(code?: string): Country {
  return COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[0]
}